repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: ^GCP-setup-steps.pdf
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        files: '\.py$'
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
    -   id: go-fmt
        files: '\.go$'
