# syntax=docker/dockerfile:1
FROM golang:1.17-alpine
ENV PORT 8080
ENV HOSTDIR 0.0.0.0

EXPOSE 8080
WORKDIR /app
COPY backend/go.mod backend/go.sum ./
RUN go mod tidy
COPY backend .env ./
RUN go build -o /main
CMD [ "/main" ]
