version: '3.8'

services:
  # postgres database
  postgresdb:
    image: postgres:16
    container_name: cbi-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mainnetwork

  backend:
    # go app
    container_name: cbi-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgresdb
    networks:
      - mainnetwork

  frontend:
    # django frontend
    container_name: cbi-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOSTDIR=0.0.0.0
    depends_on:
      - postgresdb
    networks:
      - mainnetwork

  # pgadmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: cbi-pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8085:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mainnetwork

networks:
  mainnetwork:

volumes:
  db-data:
  pgadmin-data:
